Card and about sections
Mikelobi/Personal-Portfolio pull request #1
Opened 2022-02-17 12:48 UTC by Mikelobi

**CARD AND ABOUT SECTIONS**

In this Project:

- **I added the card and about sections to the content of the project**
- **I added style to the contents of the project**
- **I created working Github action to check errors**
- **I added a readme file for further useful information about the project**

2022-02-17 14:40 UTC, Wes-Isaac requested changes
Hi @Mikelobi, 

Impressive work so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!

### 📝👌 Your project highlights 🔥😎

- Linters are on point ✔
- Splendid work with the README file 👀
- Proper use of GitHub flow 👌
- Awesome design 🙌

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 14:40 UTC, Wes-Isaac commented on style.css
> +}
- [ ] Great job so far 👍. However, there are some improvements you have to make. Although the layout of the card looks great, it's one of the project requirements to use `Flexbox` to layout individual cards, kindly fix that.
- [ ] There is a little style **(background color, font)** difference between your cards and the one on Figma.
- [ ] Please implement the button interaction like **hover, pressed**

Your Implementation | Figma Design
:---: | :---:
![image](https://user-images.githubusercontent.com/59416136/154497804-075ba525-46d6-4e42-9515-1158e3a2469f.png) | ![image](https://user-images.githubusercontent.com/59416136/154497939-30d6b837-6599-4ed7-82ac-2bf9cfa0d590.png)

2022-02-17 14:40 UTC, Wes-Isaac commented on index.html
> +        </div>
- [ ] Great job implementing the language categories, but it's better to put them inside a `ul` and each category in a `li` to me more sematic. Please change the `div` to a `ul` tag.

2022-02-17 14:40 UTC, Wes-Isaac commented on style.css
> +  letter-spacing: 0.03em;
- [ ] Great job so far, your design is using a different font than the one specified in the design, kindly fix that.
- [ ] To resemble the design please implement button interaction like hover, pressed, active.

![image](https://user-images.githubusercontent.com/59416136/154501938-841521b7-a49a-4aa7-aed8-7e60036e32d7.png)

2022-02-17 14:40 UTC, Wes-Isaac commented on style.css
> +}
- [ ] Please make sure the content of the page has the same **font, spacing, color** as the design.
Your Implementation | Figma Design
:---: | :---:
![image](https://user-images.githubusercontent.com/59416136/154503440-10b0e0b3-5b44-4db0-8059-cf6fabf49a1d.png) | ![image](https://user-images.githubusercontent.com/59416136/154503666-089041f7-4dd5-4170-8027-445606b03378.png)

2022-02-17 14:40 UTC, Wes-Isaac commented on index.html
> +          <p><a href="" class="info-link">LET'S CONNECT</a></p>
- [ ] Great job so far, although this should be a `hx (h2,h3...)` tag rather than a link inside in a paragraph tag, please fix that.

2022-02-17 20:50 UTC, prolajumokeoni requested changes
Hi @Mikelobi 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
## Highlights
- Good PR ✔️ 
- No linter errors ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 07:25 UTC, Mikelobi commented on index.html
> +        </div>
I have done it. I used the same values as given in the figman design.

2022-02-18 07:25 UTC, Mikelobi commented on index.html
> +          </li>
Thanks.

2022-02-18 07:43 UTC, ShoiraTa commented
### **STATUS: APPROVED  ✔️** 
------
Hi STUDENT,  

Your project is complete! Congratulations!  🎉💯🌟 

## OPTIONAL

- [ ] I recommend you using the same font as provided in Figma called Poppins, it is availabel in google fonts - https://fonts.google.com/specimen/Poppins

***

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 07:50 UTC, merged